change persistence

diff --git a/kubernetes/apps/home/whisper/app/helmrelease.yaml b/kubernetes/apps/home/whisper/app/helmrelease.yaml
--- a/kubernetes/apps/home/whisper/app/helmrelease.yaml
+++ b/kubernetes/apps/home/whisper/app/helmrelease.yaml
@@ -78,10 +78,54 @@ spec:
           whisper:
             port: 10300
 
+    configMaps:
+      config:
+        nameOverride: "{{ .Values.global.fullnameOverride }}-config"
+        data:
+          run: |
+            #!/bin/bash
+            # vim: ft=bash
+            # shellcheck shell=bash
+            # ==============================================================================
+            # Start Whisper service
+            # ==============================================================================
+            # NOTE: modified the original https://github.com/home-assistant/addons/blob/master/whisper/rootfs/etc/s6-overlay/s6-rc.d/whisper/run
+            # to allow for configurations outside of supervised HA
+
+            if [ "$(uname -m)" == "x86_64" ] && ! grep -qw 'avx' /proc/cpuinfo; then
+                echo "Your CPU does not support Advanced Vector Extensions (AVX). Whisper will run slower than normal." >&2
+            fi
+
+            # Read model from environment variable, default to 'tiny-en' if not set
+            model="${MODEL:-tiny-en}"
+            if [ "${model}" = "custom" ]; then
+                # Override with custom model from environment variable
+                custom_model="${CUSTOM_MODEL}"
+                if [ -z "${custom_model}" ]; then
+                    echo "Error: CUSTOM_MODEL is not set for custom model" >&2
+                    exit 1
+                fi
+                model="${custom_model}"
+            fi
+
+            # Debug logging flag
+            if [ "${DEBUG_LOGGING:-false}" = "true" ]; then
+                flags+=('--debug')
+            fi
+
+            # Execute the Whisper service
+            exec python3 -m wyoming_faster_whisper \
+                --uri 'tcp://0.0.0.0:10300' \
+                --model "${model}" \
+                --beam-size "${BEAM_SIZE:-5}" \
+                --language "${LANGUAGE:-en}" \
+                --data-dir /data \
+                --download-dir /data ${flags[@]}
 
     persistence:
       config:
         type: configMap
+        name: "{{ .Values.global.fullnameOverride }}-config"
         advancedMounts:
           whisper:
             whisper:
